### ISSUE TITLE
TypeError: '<' not supported between instances of 'ProcessorNode' and 'ProcessorNode'

### ISSUE THREAD

**Issue by singularity-xx** [wintoncode/winton-kafka-streams#37]
## Description

If the punctuations are scheduled at the same time _punctuation_queue.py will try to instances of classes which causes exception.

### Version
87728e2 (HEAD -> master, origin/master, origin/HEAD) Merge pull request #34 from 
Python 3.6.3

### How to reproduce
Timing issues can be hard to reproduce. Following fails if input-topic doesn't exists and you run python reproduce.py

### Possible fix

One way to solve issue is adding "<" operator to Processor Node class. Not a perfect one because if Python's heap implementation is changed it may call ">" operator too.

```python
class ProcessorNode:
....
  def __lt__(self, other):
        return True
```

### Stack Trace
```
(python363) ats@ubuntu-vm:~/devel$ python reproduce.py
ok
Unexpected state transition from RUNNING to ASSIGNING_PARTITIONS.
0 ProcessorNode(<class '__main__.Processor1'>(unique_users)) 1.0
PunctuationSchedule(timestamp=0, node=ProcessorNode(<class '__main__.Processor1'>(unique_users)), interval=1.0)
0 ProcessorNode(<class '__main__.Processor2'>(update_db)) 1.0
PunctuationSchedule(timestamp=0, node=ProcessorNode(<class '__main__.Processor2'>(update_db)), interval=1.0)
Unexpected state transition from ASSIGNING_PARTITIONS to NOT_RUNNING.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_thread.py", line 134, in run
    records = self.poll_requests(0.1)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_thread.py", line 157, in poll_requests
    record = self.consumer.poll(poll_timeout)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_thread.py", line 215, in on_assign
    self.add_stream_tasks(partitions)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_thread.py", line 209, in add_stream_tasks
    in grouped_tasks.items()]
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_thread.py", line 208, in <listcomp>
    for (task_id, partitions)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_task.py", line 83, in __init__
    self._init_topology(self.context)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_task.py", line 89, in _init_topology
    node.initialise(context)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/topology.py", line 22, in initialise
    self.processor.initialise(self.name, _context)
  File "reproduce.py", line 17, in initialise
    self.context.schedule(1.)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/processor_context.py", line 56, in schedule
    self.task.schedule(timestamp)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_stream_task.py", line 174, in schedule
    self.punctuation_queue.schedule(self.context.currentNode, interval)
  File "/home/ats/devel/python/python363/lib/python3.6/site-packages/winton_kafka_streams/processor/_punctuation_queue.py", line 17, in schedule
    self.pq.put(PunctuationSchedule(0, node, interval))
  File "/usr/lib/python3.6/queue.py", line 143, in put
    self._put(item)
  File "/usr/lib/python3.6/queue.py", line 227, in _put
    heappush(self.queue, item)
TypeError: '<' not supported between instances of 'ProcessorNode' and 'ProcessorNode'

Segmentation fault (core dumped)
```

### Code
```python
from winton_kafka_streams.processor import BaseProcessor, TopologyBuilder
import winton_kafka_streams.kafka_config as kafka_config
import winton_kafka_streams.kafka_streams as kafka_streams

class Processor1(BaseProcessor):
    def initialise(self, _name, _context):
        super().initialise(_name, _context)
        self.context.schedule(1.)
    def process(self, key, logline):
        pass
    def punctuate(self, timestamp):
        pass

class Processor2(BaseProcessor):
    def initialise(self, _name, _context):
        super().initialise(_name, _context)
        self.context.schedule(1.)
    def process(self, key, message):
        pass
    def punctuate(self, timestamp):
        pass

def start():

    kafka_config.read_local_config("kafka.properties")

    with TopologyBuilder() as topology_builder:
        topology_builder \
            .source('input', ['input']) \
            .processor('unique_users', Processor1, 'input') \
            .processor('update_db', Processor2, 'unique_users')

    wks = kafka_streams.KafkaStreams(topology_builder, kafka_config)
    wks.start()
    print("ok")

start()
```

**Comment by ah-** [comment]
Thanks for reporting this! I'll have a look tomorrow.

**Comment by ah-** [comment]
Fixed now, thanks for the detailed bug report!
